export class Usuario {
  constructor(
    public Id?: number,
    public NombreCompleto?: string,
    public NombreUsuario?: string,
    public Contrasenia?: string,
    public Correo?: string,
    public Telefono?: string,
    public Identificacion?: string,
    public Estado?: string,
    public NombreGrupo?: string,
    public ClienteId?: number
  ) {}
}

export class Permiso {
  public static ADMINISTRADOR = "ADMIN";

  public static CONSULTA_FULL = "CONS_FULL";
  public static CONSULTA_VENDEDOR = "CONS_VEND";
  public static CONSULTA_EXTERNA = "CONS_EXTE";
  public static CONSULTA_REPORTE_ESTADO_CUENTA = "CONS_REP_EST_CTA";
  public static REPORTES_PCA = "REP_PCA";

  /* ABC */
  public static CONSULTA_REPRESENTANTE_NEGOCIO = "RESP_NEG";
  public static ADMINISTRACION_REPORTES_ESCRITORIO = "ADM_REP_ESC";

  public static CONSULTA_PERFILAMIENTO = "CONS_PERFILAMIENTO";

  public static ACTUALIZACION = "ACTUALIZACI";
  public static MENU_REPORT_MOV_PERSONA = "MENU_REPORT_MOV_PERSONA";
  public static TABLA_REPORT_MOV_PERSONA = "TABLA_REPORT_MOV_PERSONA";

  public static CREAR_EMP = "CREAR_EMP";

  public static EMPCREA = "EMPCREA";
  //Reportes Perfilamiento
  public static REPORTE_PERFILAMIENTO_FV = "REP_PERF_FV";
  public static REPORTE_PERFILAMIENTO_SAC = "REP_PERF_SAC";
  public static REPORTE_PERFILAMIENTO_BASE_TOTAL = "REP_PERF_BASET";
  public static REPORTE_PERFILAMIENTO_LOG_CARGA = "REP_PERF_LOGCAR";
  //GCU 2020-12-27 Para actualización de contactos de la empresa
  public static EMP_ACT_CONT = "EMP_ACT_CONT";
  public static CONSULTA_DESCARGA_DOC_CON = "DESCARGA_DOC_CON";

  public static AUTORIZACIONES_FULL = "AUTH_FULL";
  public static AUTORIZACIONES_CRUD = "AUTH_CRUD";
  public static AUTORIZACIONES_TRACKING = "AUTH_TRACK";
  public static AUTORIZACIONES_REPORTE = "AUTH_REP";
  public static AUTORIZACIONES_REPORTE_IN_SITU = "AUTH_REP_SITU";
  public static AUTORIZACIONES_CATALOGO_OBSERVACIONES =
    "AUTORIZACIONES_CATALOGO_OBSERVACIONES";
  public static AUTORIZACIONES_REPORTE_EXCEPCIONES = "AUTH_REP_EXCEP";

  public static ODAS = "ODAS";
  public static ODAS_LABORATORIOS_FARMACIAS = "ODAS_LAB_FAR";
  public static TRANSACCIONES = "TX";
  public static MOVIMIENTOS_REPORTE = "REP_MOV";
  public static AUDITORIAS = "AUDIT";
  public static REPORTE_FINANCIAMIENTO = "REP_FIN";
  public static VISACIONES_REPORTE = "REP_VISA";

  //public static TRANSACCIONES_CAMBIOS = "TX_CA";
  //public static TRANSACCIONES_PAGOS = "TX_PA";
  //public static TRANSACCIONES_CONTRATOS = "TX_CO";
  //public static TRANSACCIONES_OTROS = "TX_OT";

  public static TRANSACCIONES_CAMBIO_CORRESPONDENCIA = "TX_CAMB_CORRES";
  public static TRANSACCIONES_PLAN = "TX_PL";
  public static TRANSACCIONES_MISMAS_CONDICIONES = "TX_MISMAS_CONDICIONES";
  public static TRANSACCIONES_MIGRACION_XPR = "TX_MIGRACION_XPR";
  public static TRANSACCIONES_TITULAR = "TX_TIT";
  public static TRANSACCIONES_BTN_TX_TITULAR_DIAS = "BTN_TX_TITULAR_DIAS";
  //public static TRANSACCIONES_EMPRESA = "TX_EMP";
  public static TRANSACCIONES_FORMA_PAGO = "TX_FORPAG";

  /** @internal esta variable sirve para saltar la validacion del
   * backend ValidadorCambioPeriodoPago(contratoKey, datosContratoAnterior.PeriodoPago.Value);*/
  public static TRANSACCIONES_BTN_FORMA_PAGO = "TX_BTN_FORMA_PAGO";

  public static TRANSACCIONES_PAGO_INTELIGENTE = "TX_PAGINT";
  public static TRANSACCIONES_ANULACION = "TX_ANU";
  public static TRANSACCIONES_APLICACION_DESCUENTO = "TX_APL_DESC";
  public static TRANSACCIONES_BLOQUEO_DESBLOQUEO = "TX_BLODESMO";
  public static TRANSACCIONES_FACTURACION_MANUAL = "TX_FAC_MAN";
  public static TRANSACCIONES_QUITAR_CARENCIAS = "TX_QUIT_CAR";
  public static TRANSACCIONES_TX_QUIT_CAR_RESTRINGIDO = "TX_QUIT_CAR_RESTRINGIDO";
  public static TRANSACCIONES_RENOVACION = "TX_RENOV";
  public static TRANSACCIONES_REACTIVACION = "TX_REAC";
  public static TRANSACCIONES_MANTENIMIENTO_OBS = "TX_MANOBS";
  public static TRANSACCIONES_EMISION_TARJETAS = "TX_EMITARJ";
  public static TRANSACCIONES_MOD_MATERNIDAD = "TX_MATER";
  public static TRANSACCIONES_MOD_BENEFICIARIO = "TX_MODBENE";
  public static TRANSACCIONES_SEG_DESGRAVAMEN = "TX_SEGDESGR";
  public static TRANSACCIONES_REASIGNACION_CARTERA = "TX_REASIGNACION";
  public static TRANSACCIONES_CAMBIO_FECHA_INICIO_CONTRATO = "TX_FECHA_INICIO";
  public static TRANSACCIONES_REACTIVACION_EXTEMPORANEA = "TX_REAC_EXTEM";
  public static TRANSACCIONES_CAMBIO_PLAN_PRIVILEGIOS =
    "TX_CAMBIO_PLAN_PRIVILEGIOS";
  public static TRANSACCIONES_REACTIVACION_SERVICIO_RETROACTIVO_CON_PRIVILEGIOS =
    "TX_REAC_SERV_RETRO_PRIVILEGIOS";

  public static TRANSACCIONES_INGRESO_PREEXISTENCIAS = "TXT_INGR_PREEX";
  public static TRANSACCIONES_PAGO_COMISIONES = "TXT_PAGO_COMISIONES";

  public static TRANSACCIONES_CAMBIO_EMPRESA = "TXT_CAMBIO_EMPRESA";
  public static TRANSACCIONES_PENDIENTE_VIGENTE = "TXT_PENDIENTE_VIGENTE";
  public static TRANSACCIONES_PRECIO = "TXT_PRECIO";

  public static TRANSACCIONES_REACTIVACION_BENEFICIARIO_RETROACTIVO =
    "TX_REAC_BENF_RETRO";

  public static TRANSACCIONES_SERVICIO_ADICIONAL_GRATUITO =
    "SERVICIO_ADICIONAL_GRATUITO";
  public static TRANSACCIONES_ANULACION_POST20 = "ANULACION_POST20";

  public static TRANSACCIONES_VISACION = "TX_VISACION";

  public static PRESTADORES_FULL = "PREST_FULL";
  public static PRESTADORES_CONSULTAR = "PREST_CONS";
  public static PRESTADORES_AGENDAR_CITA = "PREST_AC";
  public static PRESTADORES_CALIFICACION = "PREST_CAL";
  public static AUDITORIA_CONVENIOS = "AUD_CONV";

  //CATALOGO
  public static CATALOGOS_FULL = "CATG_FULL";
  public static CATALOGOS_DIAGNOSTICO = "CATG_DIAG";
  public static CATALOGOS_PROCEDIMIENTO = "CATG_PROC";
  public static CATALOGOS_VALOR_PUNTO = "CATG_VP";
  public static CATALOGOS_EDIT_VALOR_PUNTO = "EDIT_CATG_VP";
  public static CATALOGOS_TIPO_EMPRESA = "CATG_TIEP";
  public static CATALOGOS_RETENCION_DIFERENCIADA = "CATG_REDI";
  public static CATALOGOS_COBERTURAS = "CATG_COBE";
  public static CATALOGOS_BENEFICIOS = "CATG_BENE";
  public static CATALOGOS_DEDUCIBLES = "CATG_DEDU";
  public static CATALOGOS_GRUPO_ARANCEL = "CATG_ARAN";

  public static SIMULADOR_RESERVAS = "SIM_REV";
  public static HISTORICO_RESERVAS = "HIS_REV";
  public static REGENERACION_RESERVAS = "REG_REV";
  public static SOBRES_POR_CONTRATO = "SB_X_CTR";
  public static SOBRES_CONSULTA = "SB_CON";
  public static SOBRES_INGRESAR = "SB_ING";
  public static SOBRES_ASIGNAR = "SB_ASIG";
  public static SOBRES_REPORTE = "SB_REP";
  public static SOBRES_CONSULTOR = "SB_CNT";
  public static SOBRES_ANULAR = "SB_ANUL";
  public static SOBRES_DEVOLUCION = "SB_DEV";
  public static SOBRES_AUTORIZAR = "SB_AUT";

  public static LIQUIDACION_AUTH = "LIQUIDACION_AUTH";
  public static LIQUIDACION_TRASPASO_AUTH = "LIQUIDACION_TRASPASO_AUTH";
  public static LIQUIDACION_REEIMPRESION = "REIMP_LOT";

  public static LIQUIDACION_COBRO_FEE = "LIQUIDACION_COBRO_FEE";

  //CREDITOS
  public static INGRESAR_CREDITO = "INGR_CRED";
  public static REPORTE_CREDITO = "REP_CRED";
  public static ASIGNAR_CREDITO = "ASIG_CRED";
  public static CONSULTOR_CREDITO = "CONS_CRED";
  public static AUTORIZAR_CREDITO = "AUT_CRED";

  public static RETENCION_CONSULTA = "RET_CON";
  public static RETENCION_INFORMACION = "RET_INF";
  public static RETENCION_REPORTE = "RET_REP";
  public static RETENCION_PARAMETRO_DESCUENTO = "RET_PAR_DES";
  public static RETENCION_APROBACION = "RET_APRO";
  public static RETENCION_ANULACION = "ANU_RET";
  public static RETENCION_ANULACION_IMPUESTO = "ANU_RET_IMP";

  //Corporativo
  public static CORPORATIVO_FULL = "CORP_FULL";
  // public static CORPORATIVO_FULL = "CONS_FULL";
  public static CORPORATIVO_EMPRESA = "EMP_CORP";
  public static CORPORATIVO_GRUPO = "GRUP_CORP";
  public static CORPORATIVO_CREAR = "CREA_CORP";
  public static CORPORATIVO_TERMINOSCONDICIONES = "CORP_TC";
  public static CORPORATIVO_USUARIOSALUDADM = "USRSAL_CORP";
  public static CORP_NOTCATEGORIA = "NOTCAT_CORP";
  public static CORP_NOTENVIO = "NOTENV_CORP";
  public static CORP_RENOV = "CORP_RENOV";
  public static CORP_EXT = "CORP_EXT";
  public static CORP_MOV = "CORP_MOV";
  public static CORP_RC = "CORP_RG";
  public static CORP_REC = "CORP_REC";

  //CORREDORES
  public static FULL_BRO = "FULL_BRO";
  public static CREA_BRO = "CREA_BRO";
  public static TC_BRO = "TC_BRO";
  public static GRUP_BRO = "GRUP_BRO";
  public static REASIG_BRO = "REASIG_BRO";
  public static REP_REASIG_BRO = "REP_REASIG_BRO";
  public static NOTCATEGORIA_BRO = "NOTCAT_BRO";
  public static NOTENVIO_BRO = "NOTENV_BRO";
  public static USUARIOSALUDADM_BRO = "USRSAL_BRO";

  // COMISIONES
  public static COMISIONES_FULL = "COMS_FULL";
  public static COMISIONES_GRUPO = "COMS_GRUP";
  public static COMISIONES_AGENTEVENTA = "COMS_AGENTV";
  public static COMISIONES_AUDITORIA = "COMS_AUDIT";
  public static COMISIONES_BECAS = "COMS_BECAS";
  public static COMISIONES_TIPO = "COMS_TIPO";
  public static COMISIONES_REGION = "COMS_REGION";
  public static COMISIONES_TIPOVENDEDOR = "COMS_TIPOVENDEDOR";
  public static COMISIONES_MONTOVENTA = "COMS_MOVE";
  public static COMISIONES_BONO = "COMS_BONO";
  public static COMISIONES_CATEGORIA = "COMS_CATG";
  public static COMISIONES_BONOMENSUAL = "COMS_BONOMENSUAL";
  public static COMISIONES_BONOPLANCARRO = "COMS_BONOPC";
  public static COMISIONES_ESTADO = "COMS_ESTADO";
  public static COMISIONES_PERIODO = "COMS_PERIODO";
  public static COMISIONES_PLANCARROEJECUTIVO = "COMS_PLANCEJECUTIVO";
  public static COMISIONES_VACACIONES = "COMS_VACACIONES";
  public static COMISIONES_PREMIOSJEFESAGENCIAS = "COMS_PREMIOSJEFESAGENCIAS";
  public static COMISIONES_PREMIOS = "COMS_PREMIOS";
  public static COMISIONES_PREMIODIRECTORES = "COMS_PREMIODIRECTORES";
  public static COMISIONES_PREMIOSREQUISITOS = "COMS_PREMIOSREQUISITOS";
  public static COMISIONES_BONOMPCG = "COMS_BONOMPCG";
  public static COMISIONES_DIRECTORES = "COMS_DIRECTORES";
  public static COMISIONES_PREMIOONCARE = "COMS_PREMIOONCARE";
  public static COMISIONES_GRUPOVENDEDOR = "COMS_GRUPOVENDEDOR";
  //COMERCIAL
  public static DIRECTOR_VENTAS = "DIR_VENT";
  public static GERENTE_COMERCIAL = "GER_COMERCI";
  public static EJECUTIVO_COMERCIAL = "EJE_COMERC";
  public static VICEPRESIDENTE_COMERCIAL = "VIC_COMERC";
  public static EJECUTIVO_COMISIONES = "EJE_COMIS";
  public static ADMINISTRADOR_COMISIONES = "ADM_COMIS";
  public static CONTABILIDAD_COMISIONES = "CONTA_COMIS";

  public static ADMINISTRADOR_FUN = "ADMIN_FUN";
  public static CONSULTA_FUN = "CONS_FUN";
  public static CREA_FUN = "CREA_FUN";
  public static ASIGNA_FUN = "ASG_FUN";
  public static ANULA_FUN = "ANUL_FUN";
  public static REACTIVA_FUN = "REACT_FUN";
  public static ACTIVA_FUN_FACTURA_PREVIA = "FACTUR_PREV_FUN";

  //FACTURACION
  public static LOG_ERRORES = "LOG_ERR";
  public static PROCESO_FACTUARACION = "PROCESO_FACT";
  public static SALDOS_FAVOR = "SAL_FAV";
  public static NOTAS_CREDITO = "NOT_CRED";
  public static TAREA_PROGRAMADA_NOTAS_PCA = "PROG_NOT_PCA";
  public static TAREA_PROGRAMADA_NOTAS_LOTE = "PROG_NOT_LOT";
  public static CONSULTA_DOCS_ELECTRONICOS_DIRECTO_SRI =
    "CONSULT_DOCS_DIRECTO_SRI";
  public static COTIZACIONES_PRINCIPAL = "COTIZACIONES_PRINCIP";
  public static DESCUENTO_PARAMETRO = "CONT_DESC_PAR";
  public static ORDENES_COMPRA = "ORDENES_COMPRA";
  public static FACTURACION_IND_PREVIA = "FACT_IND_PREV";

  //AGENDAR CITA
  public static AGENDA_CITA = "AG_CITA";

  //Planes Corporativo
  public static CONSULTAR_PLANES_COR = "CONSULT_PLANES_COR";
  public static MODIFICAR_PLANES_COR = "MODIFICA_PLANES_COR";
  public static PORTAL_CLIENTES = "ADM_POR_CLI";

  //Cobranzas
  public static COBRAZAS_FULL = "GESTION_COBRANZA";
  public static COBRAZAS_IMPRESION = "COBRANZAS_IMPRE";
  public static COBRANZAS_MENU_REPORTE = "COBR_MENU_REP";

  //PRESTADORES
  public static AGENDAR_CITA_CENTRO_MEDICO = "AG_CIT_CEN_MED";
  public static SOLICITUD_MEDICO_DESTACADO = "SOL_MED";
  public static CONSULTAR_SOLICITUD = "CON_SOL";
  public static CONSULTAR_CITA = "CON_CIT";
  public static ACTUALIZAR_CONVENIO = "ACT_CONV";
  public static INGRESAR_CONVENIO = "INS_CONV";
  public static UPDATE_COORDENADAS = "UPDT_COORD_PREST";
  public static REGISTRAR_PRESTADOR_EXTRANJERO = "REG_PRE_EXT";

  //REPORTES FACTURACION
  public static REPORTE_MOROSOS_POR_COBRAR = "REP_MOR_COB";
  public static REPORTE_FACTURAS_EMITIDAS = "REP_FACT_EMI";
  public static REPORTE_CONSULTAS_PROBLEMAS = "REP_CON_PRO";

  //RECAUDOS
  public static REACAUDOS_SALUD_PAY = "REC_SALUD_PAY";
  public static REACAUDOS_BOTON_CAJA_PICHINCHA = "REC_CAJA_PICHINCHA";
  public static GENERAR_ARCHIVOS_DEBITOS_INSTITUCIONES = "GEN_ARCH_DEB_INST";
  public static INGRESO_CAJA = "INGRESO_CAJA";
  public static INGRESO_CAR_RES = "INGRESO_CAR_RES";

  // SERVICIOS ADICIONALES
  public static SRVAD_FULL = "SRVAD_FULL";
  public static SRVAD_BASES_QUERY = "SRVAD_BASES_QUERY";
  public static SRVAD_MOD_PRECIO = "SRVAD_MOD_PRECIO";

  // ADMINISTRACION DE USUARIOS
  public static ADMIN_USU_ROL = "ADMIN_USU_ROL";
  // ADMINISTRACION DE FUNCIONALIDADES
  public static ADMIN_FUNCIONALIDAD = "ADMIN_FUNCIONALIDAD";
  //ADMINISTRACION DE ROLES
  public static ADMIN_USU_ROL_ROL = "ADMIN_USU_ROL_ROL";
  //ADMINISTRACION DE EMAILS
  public static ADMIN_USU_EMAIL = "ADMIN_USU_EMAIL";

  //ADMINISTRACION DE RESERVAS
  public static REPORTE_RESERVAS = "ADMIN_REP_RESE";
  public static REPORTE_CONTABILIDAD = "ADMIN_REP_CONTA";
  public static REPORTE_PRESTADORES_MASIVOS = "MASIVOS_REP_CONTA";
  public static CONSULTA_RETENCION_FACT_PREST = "CONSULTA_RETENCION_FACT_PREST";

  //SERVICIOS ADICIONALES - PARTNERS
  public static PARTNER_SERV_ADIC_LISTBAS = "PARTNER_SERV_ADIC_LISTBAS";
  public static PARTNER_SERV_ADIC_POLIZAS = "PARTNER_SERV_ADIC_POLIZAS";
  public static PARTNER_SERV_ADIC_TICKET = "PARTNER_SERV_ADIC_TICKET";
  public static PARTNER_SERV_ADIC_REPORTES = "PARTNER_SERV_ADIC_REPORTES";

  //TICKETS COMISIONES
  public static COMISIONES_CREAR_TICKETS = "COMISIONES_CREAR_TICKETS";
  public static COMISIONES_VER_TICKETS = "COMISIONES_VER_TICKETS";
  public static COMISIONES_GESTIONAR_TICKETS = "COMISIONES_GESTIONAR_TICKETS";
  public static COMISIONES_ASIGNAR_TICKETS = "COMISIONES_ASIGNAR_TICKETS";
  public static COMISIONES_REASIGNAR_TICKETS = "COMISIONES_REASIGNAR_TICKETS";
  public static COMISIONES_VER_TICKETS_SALA = "COMISIONES_VER_TICKETS_SALA";

  //MASIVOS
  public static MASIVOS = "MASVS";
  public static MASIVOS_ANULAR_RECLAMOS = "MASVS_ANUL_ADMIN";
  public static ACTUALIZAR_PERSONA_ADMIN = "ACT_PER_ADMIN";

  //MASIVOS UNIVERSIDADES
  public static MASIVOS_UNIVERSIDADES = "MASIVOS_UNIVERSIDADES";

  //MASIVOS CONSULTAS
  public static CONSULTAS_MASIVOS = "CONSULTAS_MASIVOS";

  //MASIVOS-REIMPRIMIR SPP
  public static REIMPRIMIR_SPP = "REIMPRIMIR_SPP";

  //MASIVOS-GRUPALES
  public static MASIVOS_GRUPALES= "MAS_GRUP";

  //VITALITY
  public static VITALITY_ACCESO_TOTAL = "VITALITY_ACCESO_TOTAL";
  public static VITALITY_REPORTES = "VITALITY_REPORTES";
  public static PI_CAMB_ID_REB = "PI_CAMB_ID_REB";
  public static VITALITY_LOG_ERRORES = "VITALITY_LOG_ERRORES";
  public static VITALITY_MENU_FEES = "VITALITY_MENU_FEES";
  public static VITALITY_PARAMETRIZACION = "VITALITY_PARAMETRIZACION";
  public static VITALITY_EJECUCION_FEES = "VITALITY_EJECUCION_FEES";
  public static VITALITY_MENU_PAGOS = "VITALITY_MENU_PAGOS";
  public static VITALITY_PROCESO_PAGOS = "VITALITY_PROCESO_PAGOS";
  public static VITALITY_GESTION_REBOTES = "VITALITY_GESTION_REBOTES";
  public static VITALITY_CAMBIO_ESTADO_PAGO = "VITALITY_CAMBIO_ESTADO_PAGO";
  public static VITALITY_CONSULTA_RESPUESTAS = "VITALITY_CONSULTA_RESPUESTAS";
  public static VITALITY_CONSULTAS_GENERALES = "VITALITY_CONSULTAS_GENERALES";
  public static VITALITY_REPORTES_FINANZAS = "VITALITY_REPORTES_FINANZAS";
  public static VITALITY_CB_MANUAL = "VITALITY_CB_MANUAL";
  public static VITALITY_CONFIGURACION_RELOJ = "VITALITY_CONFIGURACION_RELOJ";

  //PAGO INTELIGENTE
  public static PI_ACCESSO_TOTAL = "PI_ACCESSO_TOTAL";

  //PAGO VENTANILLA
  public static PV_MENU_PRINCIPAL = "PV_MENU_PRINCIPAL";
  public static PV_PREST = "PV_PREST";

  public static LISTA_CORPORATIVO_PALNES = "LISTA_CORPORATIVO_PALNES";

  //CERTIFICADOS
  public static CERTIFICADOS = "CERTIFICADOS";
  public static CERTIFICADOS_CAMBIOS = "CERTIFICADOS_CAMBIOS";
  public static CERTIFICADOS_REPORTES = "CERTIFICADOS_REPORTES";

  //KIT BIENVENIDA
  public static KIT_BIENVENIDA = "KIT_BIENVENIDA";
  public static KIT_BIENVENIDA_DIGITAL = "KIT_BIENVENIDA_DIGITAL";
  //RETENCION CLIENTES
  public static RETENCION_CLIENTES = "RETENCION_CLIENTES";

  public static NOTIFICACION_COBRANZA_JEFATURA = "NOTI_COBRA_JEF";
  public static NOTIFICACION_COBRANZA = "NOTI_COBRA";
  public static REIMPRESION_RECIBO = "COBRANZAS_RE_IMPRE";

  //Reporte de cobranzas de grupales detallados
  public static REPORTE_DETALLADO_GRUPALES = "COB_REP_GRU";

  public static AUTORIZACIONES_PAQUETES = "PAQ_AUT";
  public static AUTORIZACIONES_VER_PAQUETES = "PAQ_AUT_VER";

  public static MEDIKTOR = "CONS_MEDIKTOR";
  public static ANULAR_SOBRES = "SB_ANU";

  //Autorizaciones Pago Transferencia
  public static AUTORIZACION_MONTO1 = "PAGO_TRANS_AUT_MONT1";
  public static AUTORIZACION_MONTO2 = "PAGO_TRANS_AUT_MONT2";
  public static REPORTE_SAC = "REP_SAC";
  public static CUADRE_COSTO_MENSUAL = "CUADRE_COSTO_MENSUAL";
  public static AUTORIZACION_TRANSFERENCIA = "AUTORIZACION_TRANSFERENCIA";
  public static PREPAGOS_TRANSFERENCIA = "PREPAGOS_TRANSFERENCIA";
  public static TRASPASO_CREDITO = "TRASPASO_CREDITO";
  public static CUADRE_DIARIO = "CUADRE_DIARIO";
  public static CUADRE_DIARIO_COSTO = "CUADRE_DIARIO_COSTO";

  public static TRANSACCIONES_REACTIVACION_BENEFICIARIO_RETROACTIVO_EXT =
    "TX_REAC_BENF_RETRO_EXT";

  //Reporte Mora SAC
  public static REPORTE_MORA_FULL = "REP_MORA_FULL";
  public static REPORTE_MORA_DIRECTOR = "REP_MORA_DIR";
  public static REPORTE_MORA_VENDEDOR = "REP_MORA_VEN";

  //Gestor contrato
  public static GESTOR_CONTRATO = "GESTOR_CONTRATO";
  public static CNLT_GESTOR_CONTRATO = "CNLT_GESTOR_CONTRATO";

  //Quitar Carencia Int XPR
  public static TRANSACCIONES_QUITAR_CARENCIAS_INT = "TX_QUIT_CAR_INT";
  public static TRANSACCIONES_QUITAR_REACTIVAR_CARENCIAS_INT_JEFATURA =
    "TX_QUIT_REA_CAR_INT_JEF";

  //Carga Umis
  public static CARGAR_UMIS_XPR = "CARGAR_UMIS_XPR";

  //Autoriza CambioPlan
  public static AUTORIZADO_CAMBIO_PLAN = "AUTORIZADO_CAMBIO_PLAN";
  //Archivo Texto Anulados
  public static ARCH_TEX_ANUL = "ARCH_TEX_ANUL";

  //Cambio fecha digitacion contrato
  public static CAMBIO_FECHA_DIGITACION = "CAMBIO_FECHA_DIGITACION";

  // MODULO PAGO INTELIGENTE
  public static PI_ADM_BANCOS = "PI_ADM_BANCOS";
  public static PI_PROCESAR = "PI_PROCESAR";
  public static PI_GESTION_REBOTES = "PI_GESTION_REBOTES";
  public static PI_ACREDITACIONES = "PI_ACREDITACIONES";
  public static PI_PAGOS_PRESTADOR = "PI_PAGOS_PRESTADOR";
  public static PI_CONTABILIDAD = "PI_CONTABILIDAD";
  public static PI_REP_CTAS = "PI_REP_CTAS";//este nemonico es padre de: [PI_REP_CUENTAS_PRESTADORES, PI_REP_GESTION_REBOTES, PI_REP_ACREDITACIONES]
  public static PI_REP_CUENTAS_PRESTADORES = "PI_REP_CUENTAS_PRESTADORES";
  public static PI_REP_GESTION_REBOTES = "PI_REP_GESTION_REBOTES";
  public static PI_REP_ACREDITACIONES = "PI_REP_ACREDITACIONES";
  public static REP_CC_PREST = "REP_CC_PREST";
  public static RECL_PI = "RECL_PI";
  public static PAGOS_PREST = "PAGOS_PREST";
  public static CAMBIO_ESTADO_PI = "CAMBIO_ESTADO_PI";
  //public static CAMBIO_ESTADO_PI_TES = "CAMBIO_ESTADO_PI_TES";
  public static ACT_MASIVA_POOL = "ACT_MASIVA_POOL";
  public static PI_REBOTES_REEMBOLSOS = "PI_REBOTES_REEMBOLSOS";
  public static PI_REBOTES_PRESTADORES = "PI_REBOTES_PRESTADORES";
  public static ACT_ID_CLIENTE_REBOTES = "ACT_ID_CLIENTE_REBOTES";
  public static PI_CONTA_REP_VENTANILLA = "PI_CONTA_REP_VENTANILLA";
  public static PI_CONTA_REP_REEMBOLSOS = "PI_CONTA_REP_REEMBOLSOS";
  public static PI_CONTA_REP_PRESTADORES = "PI_CONTA_REP_PRESTADORES";
  public static PI_CONTA_REP_GENERICO = "PI_CONTA_REP_GENERICO";
  public static TIPO_FORMA_PAGO_PI = "TIPO_FORMA_PAGO_PI";
  public static PI_APROBACIONES_SOLICITUD_PAGO = "PI_APROBACIONES_SOLICITUD_PAGO";



  //Reporte Contratos Digitados
  public static REP_CONT_DIG = "REP_CONT_DIG";

  //Generacion de Tarjetas
  public static GENE_TARJE = "GENE_TARJE";

  //Carga Masiva Contratos
  public static SUBI_CONT = "SUBI_CONT";

  //Administracion de Cuentas Salud
  public static CUENTAS_SALUD = "CUENTAS_SALUD";

  //Administracion Preexistencias Exoneradas
  public static PREEXISTENCIA_EXO = "PREEXISTENCIA_EXO";

  //Administracion Negociaciones
  public static NEGOCI = 'NEGOCI';

  //Nemonico Fondo Inversion
  public static FOND_INVER = "FOND_INVER";

  public static AUTOMATICO_PROCEDIMIENTOS = "AUTOMATICO_PROCEDIMIENTOS";

  //SEGURIDADES
  public static SEG_HISTORICO = "SEG_HISTORICO";
  public static SEG_ROLES = "SEG_ROLES";
  public static SEG_HIS_FUNCIONALIDAD = "SEG_HIS_FUNCIONALIDAD";
  public static SEG_DET_USUARIOS = "SEG_DET_USUARIOS";
  public static SEG_USU_ROL = "SEG_USU_ROL";
  public static SEG_LOGOUT = "SEG_LOGOUT";
  public static TCCP6A27 = "TCCP6A27";

  //Crear/editar procedimientos
  public static C_E_PROC = "C_E_PROC";

  //Oficinas SPP Farmacias
  public static OFICINAS_SPP_FARAMACIAS_COSTA = "SPSFAR_COSTA";
  public static OFICINAS_SPP_FARAMACIAS_SIERRA = "SPPFAR_SIERRA";
  public static OFICINAS_SPP_FARAMACIAS_AMBAS = "SPPFAR_TODOS";

  //Comercial Masivos/ Agente call center
  public static COM_MAS = "COM_MAS";
  public static AG_CALL_CENTER = "AG_CALL_CENTER";

  //Varios Cierres
  public static MENU_VARIOS_CIERRES = "MENU_VARIOS_CIERRES";
  //Menu SSO
  public static SSO_FULL = "SSO_FULL";
  public static SSO_CREA = "SSO_CREA";
  public static SSO_TERM = "SSO_TERM";
  public static SSO_USU = "SSO_USU";
  public static SSO_GRU = "SSO_GRU";

  //Parametrizacion Observacion
  public static PARAMETRIZACION_OBSERVACION = "PARAMETRIZACION_OBSERVACION";
  //Factura Valor Consumido
  public static FACTURA_VALOR_CONSUMIDO = "FACTURA_VALOR_CONSUMIDO";
  //Menu actualizar sobre reclamo
  public static ACTUALIZACION_SOBRE_RECLAMO = "ACTUALIZACION_SOBRE_RECLAMO";

  //Imed Medcollect Auditoria
  public static LIQUIDACION_ELECTRONICA_PLANIFICADOR =
    "LIQUIDACION_ELECTRONICA_PLANIFICADOR";
  public static LIQUIDADOR_LIQUIDACION_ELECTRONICA =
    "LIQUIDADOR_LIQUIDACION_ELECTRONICA";
  public static CONSULTA_NEGATIVA_IMED =
    "CONSULTA_NEGATIVA_IMED";

  public static CONS_FACTURAS_RECLAMOS = "CONS_FACTURAS_RECLAMOS";

  public static C_E_DIAG = "C_E_DIAG";
  //Reporte Ecuasistencia
  public static REP_ECUA = "REP_ECUASISTENCIA";

  //Reportes Armonix
  public static REP_ARMONIX = "CONTABILIDAD_REPORTES";
  public static REP_ARMONIX_SERVICIOSADICIONALES =
    "CONTABILIDAD_REPORTE_SERVICIOSADICIONALES";
  public static REP_ARMONIX_CUADREDECOSTO =
    "CONTABILIDAD_REPORTE_CUADREDECOSTO";
  public static REP_ARMONIX_ESTADOSCUENTACARTERA =
    "CONTABILIDAD_REPORTE_ESTADOSCUENTACARTERA";
  public static REP_ARMONIX_CHEQUES = "CONTABILIDAD_REPORTE_CHEQUES";
  public static REP_ARMONIX_RETELECTRONICASSRI =
    "CONTABILIDAD_REPORTE_RETELECTRONICASSRI";
  public static REP_ARMONIX_DOCUMENTOSEMITIDOS =
    "CONTABILIDAD_REPORTE_DOCUMENTOSEMITIDOS";
  public static REP_ARMONIX_GRUPALES = "CONTABILIDAD_REPORTE_GRUPALES";
  public static REP_ARMONIX_SPP = "CONTABILIDAD_REPORTE_SPP";

  public static REP_ARMONIX_CONSULTAPAGOS = "CONSULTA_PAGOS";

  public static REP_ARMONIX_MENUREPORTESRECLAMOS = "MENU_ REPORTES_RECLAMOS";
  public static REP_ARMONIX_RECLAMOS = "REPORTE_RECLAMOS";
  public static REP_ARMONIX_RECLAMOSPRESTACION = "REPORTE_RECLAMOS_PRESTACION";

  //Nemonicos administracion redes, agrupacion de redes, asignacion planes
  public static ADMRDPLN = "ADMRDPLN";
  public static AGRPRDS = "AGRPRDS";
  public static ASGNPLNGRP = "ASGNPLNGRP";

  //Reporte de Ventas Visa - PCA
  public static REP_VEN_VISA = "REP_VEN_VISA";
  //Administracino especialidades
  public static CATG_ESPE = "CATG_ESPE";
  public static MANTENEDOR_SHIFT = "MANTENEDOR_SHIFT";
  public static REPORTE_PRESTADORES_IRREGULARIDADES = "REPORTE_PRESTADORES_IRREGULARIDADES";
  public static REPORTE_RECLAMOS_PRESTADORES = "REPORTE_RECLAMOS_PRESTADORES";

  public static CAMBIAR_DATOS_LIQUIDACION = "CAMBIAR_DATOS_LIQUIDACION";

  //Cuotas masivas PCA
    public static CARGA_CUOTAS_PCA = "CARGA_CUOTAS_PCA";

  //Carga Servicio Cun
  public static CARGA_SERVICIO_CUN = "CARGA_SERVICIO_CUN";

  public static CONSULTAR_PLANES_IND = "CONSULTAR_PLANES_IND";

  //liquidacion Manual Masivos
  public static MSVLIQMAN='MSVLIQMAN';
  //Control Prepago Masivo
  public static LIQUIDADOR_PREPAGO_MASIVO = "LIQUIDADOR_PREPAGO_MASIVO";

  //Enrolamiento Vitality
  public static CAMPOS_ENROLAMIENTO_VITALITY = "CAM_ENR_VIT";

  // Tracking Consentimiento
  public static PERMISO_RENVIO_CONSENTIMIENTO = 'REENVIO_CONSENTIMIENTO';

  //Saludsa Contigo
  public static CONSULTA_SALUDASA_CONTIGO = "CONS_SALUDSA_CONTIGO";
  public static readonly CONSULTA_ALTO_COSTO = "CONS_ALTO_COSTO";

  public static MANTENEDOR_VADEMECUM = "MANTENEDOR_VADEMECUM ";
  public static ADMINISTRADOR_VADEMECUM = "ADMINISTRADOR_VADEMECUM";

  //Tarifarios
  public static ADMIN_TARIFARIO = 'ADMIN_TARIFARIO';
  public static COTIZADOR_PRESTACIONES = 'COTIZADOR_PRESTACIONES';
  public static MANTENEDOR_TARIFARIOS = 'MANTENEDOR_TARIFARIOS';

  public static NOTIFICACION_FRAUDES = 'NOTIFICACION_FRAUDES';

  public static FWA_FULL = "FWA_FULL";
  public static FWA_BENEFICIARIOS = "FWA_BENEFICIARIOS";
  public static FWA_PRESTADORES = "FWA_PRESTADORES";
  public static FWA_LIQUIDACIONES = "FWA_LIQUIDACIONES";

  public static TICKET_XPR_ZENDESK = "TICKET_XPR_ZENDESK";
  public static REPORTE_CONTACTO_PRESTADOR = "REP_CONT_PREST";

  //Ventas Cruzadas
  public static VENTAS_CRUZADAS = "VENTAS_CRUZADAS";
}
