// Constantes relacionadas con roles y permisos
export const USER_ROLES = {
  ADMIN: 'ADMIN',
  ODONTOLOGO: 'ODONTOLOGO',
  RECEPCIONISTA: 'RECEPCIONISTA',
  PACIENTE: 'PACIENTE',
} as const;

// Constantes para nombres de roles en español
export const ROLE_NAMES = {
  ADMIN: 'Administrador',
  ODONTOLOGO: 'Odontólogo',
  RECEPCIONISTA: 'Recepcionista',
  PACIENTE: 'Paciente',
} as const;

export const PERMISSIONS = {
  // Usuarios
  USERS_VIEW: 'users:view',
  USERS_CREATE: 'users:create',
  USERS_EDIT: 'users:edit',
  USERS_UPDATE: 'users:update',
  USERS_DELETE: 'users:delete',
  
  // Pacientes
  PATIENTS_VIEW: 'patients:view',
  PATIENTS_CREATE: 'patients:create',
  PATIENTS_EDIT: 'patients:edit',
  PATIENTS_UPDATE: 'patients:update',
  PATIENTS_DELETE: 'patients:delete',
  
  // Citas
  APPOINTMENTS_VIEW: 'appointments:view',
  APPOINTMENTS_CREATE: 'appointments:create',
  APPOINTMENTS_EDIT: 'appointments:edit',
  APPOINTMENTS_UPDATE: 'appointments:update',
  APPOINTMENTS_DELETE: 'appointments:delete',
  
  // Calendario
  CALENDAR_VIEW: 'calendar:view',
  
  // Clínicas
  CLINICS_VIEW: 'clinics:view',
  CLINICS_CREATE: 'clinics:create',
  CLINICS_EDIT: 'clinics:edit',
  CLINICS_UPDATE: 'clinics:update',
  CLINICS_DELETE: 'clinics:delete',
  
  // Historias clínicas
  MEDICAL_RECORDS_VIEW: 'medical-records:view',
  MEDICAL_RECORDS_CREATE: 'medical-records:create',
  MEDICAL_RECORDS_EDIT: 'medical-records:edit',
  MEDICAL_RECORDS_UPDATE: 'medical-records:update',
  MEDICAL_RECORDS_DELETE: 'medical-records:delete',
  
  // Notificaciones
  NOTIFICATIONS_VIEW: 'notifications:view',
  NOTIFICATIONS_VER: 'NOTIFICACIONES_VER',
  
  // Pagos
  PAYMENTS_VIEW: 'payments:view',
  PAYMENTS_CREATE: 'payments:create',
  PAYMENTS_EDIT: 'payments:edit',
  PAYMENTS_UPDATE: 'payments:update',
  PAYMENTS_DELETE: 'payments:delete',
} as const;

export const ROLE_PERMISSIONS = {
  [USER_ROLES.ADMIN]: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.PATIENTS_VIEW,
    PERMISSIONS.PATIENTS_CREATE,
    PERMISSIONS.PATIENTS_EDIT,
    PERMISSIONS.PATIENTS_UPDATE,
    PERMISSIONS.PATIENTS_DELETE,
    PERMISSIONS.APPOINTMENTS_VIEW,
    PERMISSIONS.APPOINTMENTS_CREATE,
    PERMISSIONS.APPOINTMENTS_EDIT,
    PERMISSIONS.APPOINTMENTS_UPDATE,
    PERMISSIONS.APPOINTMENTS_DELETE,
    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.CLINICS_VIEW,
    PERMISSIONS.CLINICS_CREATE,
    PERMISSIONS.CLINICS_EDIT,
    PERMISSIONS.CLINICS_UPDATE,
    PERMISSIONS.CLINICS_DELETE,
    PERMISSIONS.MEDICAL_RECORDS_VIEW,
    PERMISSIONS.MEDICAL_RECORDS_CREATE,
    PERMISSIONS.MEDICAL_RECORDS_EDIT,
    PERMISSIONS.MEDICAL_RECORDS_UPDATE,
    PERMISSIONS.MEDICAL_RECORDS_DELETE,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.PAYMENTS_EDIT,
    PERMISSIONS.PAYMENTS_UPDATE,
    PERMISSIONS.PAYMENTS_DELETE,
  ],
  [USER_ROLES.ODONTOLOGO]: [
    PERMISSIONS.PATIENTS_VIEW,
    PERMISSIONS.PATIENTS_CREATE,
    PERMISSIONS.PATIENTS_EDIT,
    PERMISSIONS.APPOINTMENTS_VIEW,
    PERMISSIONS.APPOINTMENTS_CREATE,
    PERMISSIONS.APPOINTMENTS_EDIT,
    PERMISSIONS.APPOINTMENTS_UPDATE,
    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.MEDICAL_RECORDS_VIEW,
    PERMISSIONS.MEDICAL_RECORDS_CREATE,
    PERMISSIONS.MEDICAL_RECORDS_EDIT,
    PERMISSIONS.MEDICAL_RECORDS_UPDATE,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
  [USER_ROLES.RECEPCIONISTA]: [
    PERMISSIONS.PATIENTS_VIEW,
    PERMISSIONS.PATIENTS_CREATE,
    PERMISSIONS.APPOINTMENTS_VIEW,
    PERMISSIONS.APPOINTMENTS_CREATE,
    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
  [USER_ROLES.PACIENTE]: [
    PERMISSIONS.APPOINTMENTS_VIEW,
    PERMISSIONS.MEDICAL_RECORDS_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
} as const;
